"""Initial migration with initial roles setup

Revision ID: 8e26df64662b
Revises: 
Create Date: 2022-12-15 01:45:14.015895

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e26df64662b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('description', sa.String(length=2000), nullable=False),
                    sa.Column('tag', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('revoked_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('jti', sa.String(length=120), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    role = op.create_table('role', sa.Column('id', sa.Integer(), nullable=False),
                           sa.Column('name', sa.String(length=45), nullable=True), sa.PrimaryKeyConstraint('id'),
                           sa.UniqueConstraint('name'))
    op.bulk_insert(role, [{'id': 1, 'name': 'user'}, {'id': 2, 'name': 'coach'}, {'id': 3, 'name': 'admin'}])
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(length=120), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('fullname', sa.String(length=255), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('registrationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('schedule',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start', sa.DateTime(), nullable=False),
                    sa.Column('end', sa.DateTime(), nullable=False),
                    sa.Column('participants', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subscription_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('session_count', sa.Integer(), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users_courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users_roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('appointment',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.Column('schedule_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subscription',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start', sa.DateTime(), nullable=False),
                    sa.Column('end', sa.DateTime(), nullable=False),
                    sa.Column('session_number', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('subscription_type_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['subscription_type_id'], ['subscription_type.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users_appointments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('appointment_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_appointments')
    op.drop_table('subscription')
    op.drop_table('appointment')
    op.drop_table('users_roles')
    op.drop_table('users_courses')
    op.drop_table('subscription_type')
    op.drop_table('schedule')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('revoked_tokens')
    op.drop_table('course')
    # ### end Alembic commands ###
